[package]
name = "programs"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.3", default-features = false, features = ['std'] }
nssa-core = { path = "../../core" }
