[package]
name = "sequencer_core"
version = "0.1.0"
edition = "2021"

[dependencies]
hex.workspace = true
anyhow.workspace = true
serde_json.workspace = true
env_logger.workspace = true
log.workspace = true
serde.workspace = true
rand.workspace = true
elliptic-curve.workspace = true
k256.workspace = true

[dependencies.storage]
path = "../storage"

[dependencies.mempool]
path = "../mempool"

[dependencies.accounts]
path = "../accounts"

[dependencies.common]
path = "../common"

[dependencies.secp256k1-zkp]
workspace = true
features = ["std", "rand-std", "rand", "serde", "global-context"]
