[package]
name = "nssa-core"
version = "0.1.0"
edition = "2024"

[dependencies]
risc0-zkvm = { version = "2.3.1"}
serde = { version = "1.0", default-features = false }
thiserror = { version = "2.0.12", optional = true }
bytemuck = { version = "1.13", optional = true }
chacha20 = { version = "0.9", default-features = false }
k256 = "0.13.3"

[features]
default = []
host = ["thiserror", "bytemuck"]
