[package]
name = "example_program_deployment_programs"
version = "0.1.0"
edition = "2024"

[dependencies]
nssa_core.workspace = true

hex.workspace = true
bytemuck.workspace = true
risc0-zkvm.workspace = true
