[package]
name = "nssa"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
risc0-zkvm = "2.3.1"
nssa-core = { path = "core" }
program-methods = { path = "program_methods" }
serde = "1.0.219"
serde_cbor = "0.11.2"
sha2 = "0.10.9"

[dev-dependencies]
test-program-methods = { path = "test_program_methods" }
