[package]
name = "integration_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
actix.workspace = true

actix-web.workspace = true
tokio.workspace = true
hex.workspace = true
tempfile.workspace = true

[dependencies.clap]
features = ["derive", "env"]
workspace = true

[dependencies.sequencer_core]
path = "../sequencer_core"

[dependencies.sequencer_runner]
path = "../sequencer_runner"

[dependencies.wallet]
path = "../wallet"

[dependencies.common]
path = "../common"
