services:
  sequencer_runner:
    image: lssa/sequencer_runner
    build:
      context: ..
      dockerfile: sequencer_runner/Dockerfile
    container_name: sequencer_runner
    ports:
      - "3040:3040"
    volumes:
      # Mount configuration folder
      - ./configs/docker:/etc/sequencer_runner
      # Mount data folder
      - ./data:/var/lib/sequencer_runner
