[package]
name = "mempool"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
